version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend-image
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/CCS
      - UTFPR_BASE_URI=https://webapp.utfpr.edu.br/portalAluno/ws
      - JWT_SECRET=$(openssl rand -hex 32)  # Generate a random 256-bit hex string
    depends_on:
      - mongodb
    networks:
      - ccs-network

  mongodb:
    image: mongo:latest
    command: 
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo-data:/data/db
    networks:
      - ccs-network

networks:
  ccs-network:
    driver: bridge
